# Generated by Django 4.0.1 on 2022-01-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.BigAutoField(db_column='ID_Client', primary_key=True, serialize=False)),
                ('cnp', models.CharField(db_column='CNP', max_length=13, unique=True)),
                ('nume', models.CharField(db_column='Nume', max_length=45)),
                ('prenume', models.CharField(db_column='Prenume', max_length=45)),
                ('telefon', models.CharField(db_column='Telefon', max_length=13)),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('adresa', models.CharField(db_column='Adresa', max_length=45)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clienți',
                'db_table': 'CLIENTI',
                'ordering': ['nume', 'prenume'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id_contract', models.BigAutoField(db_column='ID_Contract', primary_key=True, serialize=False)),
                ('team_name', models.CharField(db_column='Team_name', max_length=45)),
                ('urgent', models.CharField(blank=True, db_column='Urgent', max_length=2, null=True)),
                ('deadline', models.DateField(db_column='Deadline')),
                ('pret', models.BigIntegerField(db_column='Pret')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracte',
                'db_table': 'CONTRACTE',
                'ordering': ['team_name', 'urgent'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proiect',
            fields=[
                ('id_proiect', models.BigAutoField(db_column='ID_Proiect', primary_key=True, serialize=False)),
                ('nume', models.CharField(db_column='Nume', max_length=45)),
                ('status', models.CharField(db_column='Status', max_length=45)),
                ('tip', models.CharField(db_column='Tip', max_length=45)),
                ('start_date', models.DateField(blank=True, db_column='Start_date', null=True)),
                ('finish_date', models.DateField(blank=True, db_column='Finish_date', null=True)),
            ],
            options={
                'verbose_name': 'Proiect',
                'verbose_name_plural': 'Proiecte',
                'db_table': 'PROIECT',
                'ordering': ['nume'],
                'managed': False,
            },
        ),
    ]
